variables:
  REPORT_FILENAME: gl-sast-report.json
  MAJOR: 2
  MAX_IMAGE_SIZE_BYTE: 180713000
  MAX_SCAN_DURATION_SECONDS: 100

include:
  - https://gitlab.com/gitlab-org/security-products/ci-templates/raw/master/includes-dev/analyzer.yml
