variables:
  REPORT_FILENAME: gl-sast-report.json
  MAJOR: 2
  MAX_IMAGE_SIZE_MB: 204
  MAX_SCAN_DURATION_SECONDS: 100

include:
  - https://gitlab.com/gitlab-org/security-products/ci-templates/raw/master/includes-dev/analyzer.yml

go-qa:
  extends: .qa-downstream-sast
  trigger:
    project: gitlab-org/security-products/tests/go

go-gosec-config-qa:
  extends: .qa-downstream-sast
  trigger:
    project: gitlab-org/security-products/tests/go
    branch: gosec-config-FREEZE

go-modules-qa:
  extends: .qa-downstream-sast
  trigger:
    project: gitlab-org/security-products/tests/go-modules
